# Problem Set 6: Text Analysis of DOJ Press Releases, Part 1

- For background:
    - DOJ is the federal law enforcement agency responsible for federal prosecutions; this contrasts with the local prosecutions in the Cook County dataset we analyzed earlier. Here's a short explainer on which crimes get prosecuted federally versus locally: https://www.criminaldefenselawyer.com/resources/criminal-defense/federal-crime/state-vs-federal-crimes.htm#:~:text=Federal%20criminal%20prosecutions%20are%20handled,of%20state%20and%20local%20law. 
    - Here's the Kaggle that contains the data: https://www.kaggle.com/jbencina/department-of-justice-20092018-press-releases

0.0 Import packages

In [10]:
## helpful packages
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import random
import re
import string

## Install relevant packages if you haven't already
## ! conda activate qss20
## ! conda install nltk spacy vaderSentiment gensim scikit-learn "scipy<1.13"

## nltk imports
import nltk
nltk.download('averaged_perceptron_tagger_eng')
### uncomment and run these lines if you haven't downloaded relevant nltk add-ons yet
#nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
from nltk import pos_tag
from nltk.tokenize import word_tokenize, wordpunct_tokenize
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords

## spacy imports
import spacy
### uncomment and run the below line if you haven't loaded the en_core_web_sm library yet
### ! python -m spacy download en_core_web_sm
import en_core_web_sm
nlp = en_core_web_sm.load()

## vectorizer
from sklearn.feature_extraction.text import CountVectorizer

## sentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

## LDA
from gensim import corpora
import gensim

## repeated printouts and wide-format text
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_colwidth', None)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/vivianaperez/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vivianaperez/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

0.1 Load and clean text data

In [59]:
## first, unzip the file pset6_inputdata.zip 
## then, run this code to load the unzipped json file and convert to a dataframe
## (may need to change the pathname depending on where you store stuff)
## and convert some of the attributes from lists to values

doj = pd.read_json("combined.json", lines = True)

## due to json, topics are in a list so remove them and concatenate with ;
doj['topics_clean'] = ["; ".join(topic) 
                      if len(topic) > 0 else "No topic" 
                      for topic in doj.topics]

## similarly with components
doj['components_clean'] = ["; ".join(comp) 
                           if len(comp) > 0 else "No component" 
                           for comp in doj.components]

## drop older columns from data
doj = doj[['id', 'title', 'contents', 'date', 'topics_clean', 
           'components_clean']].copy()

doj.head()

        id  \
0     None
1  12-919
2  11-1002
3   10-015
4   18-898

                                                                                                          title  \
0                                                                  Convicted Bomb Plotter Sentenced to 30 Years
1                              $1 Million in Restitution Payments Announced to Preserve North Carolina Wetlands
2                 $1 Million Settlement Reached for Natural Resource Damages at Superfund Site in Massachusetts
3                                          10 Las Vegas Men Indicted \r\nfor Falsifying Vehicle Emissions Tests
4  $100 Million Settlement Will Speed Cleanup Work at Centredale Manor Superfund Site in North Providence, R.I.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          contents  \
0  PORTLAND, Oregon. – Mohamed Osman Mohamud, 23, who was convicted in 2013 of attempting to use a weapon of mass destruction (explosives) in connection with a plot to detonate a vehicle bomb at an annual Christmas tree lighting ceremony in Portland, was sentenced today to serve 30 years in prison, followed by a lifetime term of supervised release. Mohamud, a naturalized U.S. citizen from Somalia and former resident of Corvallis, Oregon, was arrested on Nov. 26, 2010, after he attempted to detonate what he believed to be an explosives-laden van that was parked near the tree lighting ceremony in Portland.  The arrest was the culmination of a long-term undercover operation, during which Mohamud was monitored closely for months as his bomb plot developed.  The device was in fact inert, and the public was never in danger from the device. At sentencing, United States District Court Judge Garr M. King, who presided over Mohamed’s 14-day trial, said “the intended crime was horrific,” and that the defendant, even though he was presented with options by undercover FBI employees, “never once expressed a change of heart.”  King further noted that the Christmas tree ceremony was attended by up to 10,000 people, and that the defendant “wanted everyone to leave either dead or injured.”  King said his sentence was necessary in view of the seriousness of the crime and to serve as deterrence to others who might consider similar acts.     “With today’s sentencing, Mohamed Osman Mohamud is being held accountable for his attempted use of what he believed to be a massive bomb to attack innocent civilians attending a public Christmas tree lighting ceremony in Portland,” said John P. Carlin, Assistant Attorney General for National Security.  “The evidence clearly indicated that Mohamud was intent on killing as many people as possible with his attack.  Fortunately, law enforcement was able to identify him as a threat, insert themselves in the place of a terrorist that Mohamud was trying to contact, and thwart Mohamud’s efforts to conduct an attack on our soil.  This case highlights how the use of undercover operations against would-be terrorists allows us to engage and disrupt those who wish to commit horrific acts of violence against the innocent public.  The many agents, analysts, and prosecutors who have worked on this case deserve great credit for their roles in protecting Portland from the threat posed by this defendant and ensuring that he was brought to justice.” “This trial provided a rare glimpse into the techniques Al Qaeda employs to radicalize home-grown extremists,” said Amanda Marshall, U.S. Attorney for the District of Oregon.  “With the sentencing today, the court has held this defendant accountable.   I thank the dedicated professionals in the law enforcement and intelligence communities who were responsible for this successful outcome.  I look forward to our continued work with Muslim communities in Oregon who are committed to ensuring that all young people are safe from extremists who seek to radicalize others to engage in violence.”  According to the trial evidence, in February 2009, Mohamud began communicating via e-mail with Samir Khan, a now-deceased al Qaeda terrorist who published Jihad Recollections, an online magazine that advocated violent jihad, and who also published Inspire, the official magazine of al-Qaeda in the Arabian Peninsula.  Between February and August 2009, Mohamed exchanged approximately 150 emails with Khan.  Mohamud wrote several articles for Jihad Recollections that were published under assumed names. In August 2009, Mohamud was in email contact with Amro Al-Ali, a Saudi national who was in Yemen at the time and is today in custody in Saudi Arabia for terrorism offenses.  Al-Ali sent Mohamud detailed e-mails designed to facilitate Mohamud’s travel to Yemen to train for violent jihad.  In December 2009, while Al-Ali was in the northwest frontier province of Pakistan, Mohamud and Al-Ali discussed the possibility of Mohamud traveling to Pakistan to join Al-Ali in terrorist activities. Mohamud responded to Al-Ali in an e-mail: “yes, that would be wonderful, just tell me what I need to do.”  Al-Ali referred Mohamud to a second associate overseas and provided Mohamud with a name and email address to facilitate the process. In the following months, Mohamud made several unsuccessful attempts to contact Al-Ali’s associate.  Ultimately, an FBI undercover operative contacted Mohamud via email under the guise of being an associate of Al-Ali’s.  Mohamud and the FBI undercover operative agreed to meet in Portland in July 2010.  At the meeting, Mohamud told the FBI undercover operative he had written articles that were published in Jihad Recollections.  Mohamud also said that he wanted to become “operational.”  Asked what he meant by “operational,” Mohamud said he wanted to put an explosion together, but needed help. According to evidence presented at trial, at a meeting in August 2010, Mohamud told undercover FBI operatives he had been thinking of committing violent jihad since the age of 15.  Mohamud then told the undercover FBI operatives that he had identified a potential target for a bomb: the annual Christmas tree lighting ceremony in Portland’s Pioneer Courthouse Square on Nov. 26, 2010.  The undercover FBI operatives cautioned Mohamud several times about the seriousness of this plan, noting there would be many people at the event, including children, and emphasized that Mohamud could abandon his attack plans at any time with no shame.  Mohamud indicated the deaths would be justified and that he would not mind carrying out a suicide attack on the crowd. According to evidence presented at trial, in the ensuing months Mohamud continued to express his interest in carrying out the attack and worked on logistics.  On Nov. 4, 2010, Mohamud and the undercover FBI operatives traveled to a remote location in Lincoln County, Oregon, where they detonated a bomb concealed in a backpack as a trial run for the upcoming attack.  During the drive back to Corvallis, Mohamud was asked if was capable looking at all the bodies of those who would be killed during the explosion.  In response, Mohamud noted, “I want whoever is attending that event to be, to leave either dead or injured.”  Mohamud later recorded a video of himself, with the assistance of the undercover FBI operatives, in which he read a statement that offered his rationale for his bomb attack.  On Nov. 18, 2010, undercover FBI operatives picked up Mohamud to travel to Portland to finalize the details of the attack.  On Nov. 26, 2010, just hours before the planned attack, Mohamud examined the 1,800 pound bomb in the van and remarked that it was “beautiful.”  Later that day, Mohamud was arrested after he attempted to remotely detonate the inert vehicle bomb rked near the Christmas tree lighting ceremony This case was investigated by the FBI, with assistance from the Oregon State Police, the Corvallis Police Department, the Lincoln County Sheriff’s Office and the Portland Police Bureau.  The prosecution was handled by Assistant U.S. Attorneys Ethan D. Knight and Pamala Holsinger from the U.S. Attorney’s Office for the District of Oregon.  Trial Attorney Jolie F. Zimmerman, from the Counterterrorism Section of the Justice Department’s National Security Division, assisted. # # # 14-1077

## 1. Tagging and sentiment scoring (17 points)

Focus on the following press release: `id` == "17-1204" about this pharmaceutical kickback prosecution: https://www.forbes.com/sites/michelatindera/2017/11/16/fentanyl-billionaire-john-kapoor-to-plead-not-guilty-in-opioid-kickback-case/?sh=21b8574d6c6c 

The `contents` column is the one we're treating as a document. You may need to to convert it from a pandas series to a single string.

We'll call the raw string of this press release `pharma`

In [3]:
## your code to subset to one press release and take the string

# subsets to id 17-1204
pharma_df = doj[doj['id'] == "17-1204"]

# makes into a single string
pharma = pharma_df['contents'].iloc[0]

# check
print(pharma[:500])

The founder and majority owner of Insys Therapeutics Inc., was arrested today and charged with leading a nationwide conspiracy to profit by using bribes and fraud to cause the illegal distribution of a Fentanyl spray intended for cancer patients experiencing breakthrough pain. "More than 20,000 Americans died of synthetic opioid overdoses last year, and millions are addicted to opioids. And yet some medical professionals would rather take advantage of the addicts than try to help them," said Att

### 1.1 part of speech tagging (3 points)

A. Preprocess the `pharma` press release to remove all punctuation / digits (you can use `.isalpha()` to subset)

B. With the preprocessed press release from part A, use the part of speech tagger within nltk to tag all the words in that one press release with their part of speech. 

C. Using the output from B, extract the adjectives and sort those adjectives from most occurrences to fewest occurrences. Print a dataframe with the 5 most frequent adjectives and their counts in the `pharma` release. See here for a list of the names of adjectives within nltk: https://pythonprogramming.net/natural-language-toolkit-nltk-part-speech-tagging/

**Resources**:

- Documentation for `.isalpha()`: https://www.w3schools.com/python/ref_string_isalpha.asp

In [ ]:
# part a
# split into tokens based on spaces
tokens = pharma.split()

# keeps only the alphabetic tokens and converts to all lowercase
tokens_alpha = [word.lower() for word in tokens if word.isalpha()]

# check
print(tokens_alpha[:20])

['the', 'founder', 'and', 'majority', 'owner', 'of', 'insys', 'therapeutics', 'was', 'arrested', 'today', 'and', 'charged', 'with', 'leading', 'a', 'nationwide', 'conspiracy', 'to', 'profit']

In [ ]:
# part b
# tags the tokens by part of speach 
tagged_tokens = pos_tag(tokens)

#(part c)
# extracts adjectives
adjectives = [word for word, tag in tagged_tokens 
              if tag in ['JJ', 'JJR', 'JJS']]
# makes into a dataframe
adj_df = pd.DataFrame(adjectives, columns=['adjective'])
# counts occurrences of adjectives and renames col
adj_counts = adj_df.value_counts().reset_index()

adj_counts.head(5)

    adjective  count
0      former      8
1      opioid      5
2  nationwide      4
3   addictive      3
4       other      3

## 1.2 named entity recognition (4 points)

A. Using the original `pharma` press release (so the one before stripping punctuation/digits), use spaCy to extract all named entities from the press release.

B. Print the unique named entities with the tag: `LAW`

In [41]:
# part a
doc = nlp(pharma)  

# getting named entities as tuples
entities = [(ent.text, ent.label_) for ent in doc.ents]

# check
entities[:20]

[('Insys Therapeutics Inc.', 'ORG'),
 ('today', 'DATE'),
 ('Fentanyl', 'PERSON'),
 ('More than 20,000', 'CARDINAL'),
 ('Americans', 'NORP'),
 ('last year', 'DATE'),
 ('millions', 'CARDINAL'),
 ('Jeff Sessions', 'PERSON'),
 ('This Justice Department', 'ORG'),
 ('Trump', 'PERSON'),
 ('American', 'NORP'),
 ('”John N. Kapoor', 'PERSON'),
 ('74', 'DATE'),
 ('Phoenix', 'GPE'),
 ('Ariz.', 'GPE'),
 ('the Board of Directors', 'ORG'),
 ('Insys', 'FAC'),
 ('this morning', 'TIME'),
 ('Arizona', 'GPE'),
 ('RICO', 'LAW')]

In [42]:
# part b
law_entities = list(set([ent.text 
                         for ent in doc.ents 
                         if ent.label_ == "LAW"]))

print(law_entities)

['the Controlled Substances Act', 'RICO']

C. Use Google to summarize in one sentence what the `RICO` named entity means and why this might apply to a pharmaceutical kickbacks case (and not just a mafia case...)

RICO  is a law that allows prosecutors to charge people who particiapte in an organized pattern of criminal activity, which can apply to pharmacutical kickbacks if executives worked together in a coordinated scheme.

In [ ]:
## your code here

D. You want to extract the possible sentence lengths the CEO is facing; pull out the named entities with (1) the label `DATE` and (2) that contain the word year or years (hint: you may want to use the `re` module for that second part). Print these named entities.

In [45]:
# extract sentence length
sentence_lengths = []

for ent in doc.ents:
    if ent.label_ == "DATE":
        if re.search(r'\byears?\b', ent.text.lower()):
            sentence_lengths.append(ent.text)

print(sentence_lengths)

['last year', '20 years', 'three years', 'five years', 'three years']

E. Pull and print the original parts of the press releases where those year lengths are mentioned (e.g., the sentences or rough region of the press release). Describe in your own words (1 sentence) what length of sentence (prison) and probation (supervised release) the CEO may be facing if convicted after this indictment (if there are multiple lengths mentioned describe the maximum). 

**Hint**: you may want to use re.search or re.findall 

- For part E, you can use `re.search` and `re.findall`, or anything that works 😳.

In [ ]:
# splits into sentences by period
sentences = re.split(r'(?<=[.!?])\s+', pharma)

relevant_sentences = []

# goes through all sentences and checks if it has 'year' or 'years'
for sentence in sentences:
    if re.search(r'\byears?\b', sentence.lower()):
        relevant_sentences.append(sentence)

# print them
for s in relevant_sentences:
    print(s)

# if convidencted, the ceo could face up to 20 years with three years 
# of supervised release for the RICO charges and up to five years in prison
# with three years of supervised realise of the Anti-Kickback charge.

"More than 20,000 Americans died of synthetic opioid overdoses last year, and millions are addicted to opioids.
Neves, Special Agent in Charge of the VA OIG Northeast Field Office.The charges of conspiracy to commit RICO and conspiracy to commit mail and wire fraud each provide for a sentence of no greater than 20 years in prison, three years of supervised release and a fine of $250,000, or twice the amount of pecuniary gain or loss.
The charges of conspiracy to violate the Anti-Kickback Law provide for a sentence of no greater than five years in prison, three years of supervised release and a $25,000 fine.

## 1.3 sentiment analysis  (10 points)

A. Subset the press releases to those labeled with one of three topics via `topics_clean`: Civil Rights, Hate Crimes, and Project Safe Childhood. We'll call this `doj_subset` going forward and it should have 717 rows.

In [ ]:
## your code here for subsetting
# subset to the three topics
doj_subset = doj[doj['topics_clean'].str.contains(
    r'Civil Rights|Hate Crimes|Project Safe Childhood',
    regex=True
)].copy()

# check
doj_subset.shape # cant get 717 :(

(856, 6)

(856, 6)

B. Write a function that takes one press release string as an input and:

- Removes named entities from each press release string (**Hint**: you may want to use `re.sub` with an or condition)
- Scores the sentiment of the entire press release using the `SentimentIntensityAnalyzer` and `polarity_scores`
- Returns the length-four (negative, positive, neutral, compound) sentiment dictionary (any order is fine)

Apply that function to each of the press releases in `doj_subset`. 

**Hints**: 

- A function + list comprehension to execute will takes about 30 seconds on a respectable local machine and about 2 mins on jhub; if it's taking a very long time, you may want to check your code for inefficiencies. If you can't fix those, for partial credit on this part/full credit on remainder, you can take a small random sample of the 717

In [ ]:
# defining function
def sentiment_no_entities(text):
    # processes text
    doc = nlp(text)
    
    # creates a regex pattern matching the  named entities
    entities = [re.escape(ent.text) for ent in doc.ents]
    if entities:
        pattern = r'\b(?:' + '|'.join(entities) + r')\b'
        text_no_entities = re.sub(pattern, '', text)
    else:
        text_no_entities = text
    
    # sentiment
    sentiment = analyzer.polarity_scores(text_no_entities)
    return sentiment

In [ ]:
## your code here executing the function
sentiment_results = [sentiment_no_entities(text) 
                     for text in doj_subset['contents']]

sentiment_df = pd.DataFrame(sentiment_results)

# check
sentiment_df.head()

     neg    neu    pos  compound
0  0.141  0.758  0.101   -0.9920
1  0.199  0.752  0.049   -0.9931
2  0.132  0.800  0.068   -0.9325
3  0.092  0.832  0.076   -0.7579
4  0.125  0.792  0.084   -0.9037

C. Add the four sentiment scores to the `doj_subset` dataframe to create a dataframe: `doj_subset_wscore`. Sort from highest neg to lowest neg score and print the top `id`, `contents`, and `neg` columns of the two most neg press releases. 

Notes:

- Don't worry if your sentiment score differs slightly from our output on GitHub; differences in preprocessing can lead to diff scores

In [ ]:
# resets index
doj_subset_wscore = doj_subset.reset_index(drop=True).copy()

doj_subset_wscore[['neg', 'neu', 'pos', 'compound']] = sentiment_df

# sorts by sentiment
doj_sorted_neg = doj_subset_wscore.sort_values(by='neg', ascending=False)
doj_sorted_neg[['id', 'contents', 'neg']].head(2) # these two are the most negative

        id  \
0   16-659
1  17-1235
2  15-1522
3   16-213
4   16-381

                                                                                                                      title  \
0                                                       Additional Defendants Sentenced for Roles in Sex Trafficking Scheme
1  Additional Former Correctional Officer Pleads Guilty to Beating of Handcuffed and Shackled Inmate at Angola State Prison
2                                                            Alabama Man Found Guilty of Aggravated Sexual Abuse of a Child
3                                                        Alabama Man Indicted on Child Pornography and Sex Tourism Charges
4                                           Alabama Man Indicted for Producing Child Pornography Involving Multiple Victims

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          contents  \
0  Sex Trafficking Scheme Used Threats, Violence and Coercion to Compel Women into Prostitution in New Orleans and Elsewhere Additional defendants were sentenced today for their respective roles in a sex trafficking scheme operated out of the Riviera Motel in New Orleans, which compelled multiple women to engage in prostitution in New Orleans and elsewhere, announced Principal Deputy Assistant Attorney General Vanita Gupta, head of the Justice Department’s Civil Rights Division, and U.S. Attorney Kenneth A. Polite of the Eastern District of Louisiana.  Duane Phillips, 31, was sentenced to 251 months in prison; Anthony Ellis, 27, was sentenced to 15 years in prison; and Zacchaeus Taylor, 23, was sentenced to 99 months in prison.  Phillips, Ellis and Taylor are all from Memphis, Tennessee.  Restitution for the victims will be determined at a separate hearing on July 13, 2016.    On April 20, 2015, Phillips and Ellis pleaded guilty to conspiracy to engage in sex trafficking by force, fraud and coercion.  Ellis also pleaded guilty to interstate transportation for prostitution.  On June 25, 2014, Taylor pleaded guilty to conspiracy to engage in sex trafficking and to interstate transportation for prostitution.  “People who engage in human trafficking violate the most basic standards of human decency,” said Principal Deputy Assistant Attorney General Gupta.  “The Civil Rights Division is unwavering in our commitment to seeking justice on behalf of vulnerable individuals and to holding human traffickers accountable.” “Ending human trafficking is a critical priority in this district,” said U.S. Attorney Polite.  “The lengthy sentences imposed today should stand as a warning to would-be traffickers that we are investing considerable federal resources into combating this criminality.” “Today’s sentencing of these four defendants brings an end to their mistreatment and abuse of women,” said Special Agent in Charge Jeffrey S. Sallet of the FBI’s New Orleans Division.  “The FBI Child Exploitation/Human Trafficking Task Force, in conjunction with the Department of Justice, HSI and our other state and local partners, will continue to investigate and bring justice for all victims of human trafficking throughout Louisiana.” “Human trafficking is a form of modern-day slavery that ICE Homeland Security Investigations fights as one of its highest priorities via a coordinated global effort with the FBI and our state and local law enforcement partners,” said Special Agent in Charge Raymond R. Parmer Jr. of U.S. Immigration and Customs Enforcement’s Homeland Security Investigations (ICE-HSI) New Orleans.  “The results speak for themselves: over the past two years HSI has doubled its number of human trafficking arrests.  HSI will continue to investigate and seek prosecution of these criminals while also ensuring the victims of this terrible crime are rescued and get the care they need.” During their respective plea hearings and in their respective court filings, Phillips and Ellis admitted that they, along with their co-defendants Granville Robinson, Christopher Williams and Laquentin Brown, conspired to recruit, groom, force, compel and coerce adult women to engage in prostitution, enforcing rules and means of control that included requiring the women to earn a certain amount of money each day, requiring them to turn over the proceeds and prohibiting them from speaking to or looking at other pimps.  To enforce the rules, Phillips, Ellis and another defendant each admitted that they and their co-conspirators used a variety of punishments, including withholding food and forcing the victims to engage in additional commercial sex acts, as well as physical assaults.  Phillips and Ellis each admitted that they and their co-conspirators consulted one another on means of furthering their pimping activities and would monitor each other’s victims when a co-conspirator was incarcerated.  The defendants also admitted that they brought women to other cities, including Washington, D.C., and Baltimore, for coerced prostitution. According to his plea agreement, Taylor, who was charged separately, admitted that he met Phillips in 2012 and agreed to become Phillips’ protégé.  After learning the strict rules that Phillips, Ellis and others used to force and coerce women to engage in prostitution, Taylor began applying the rules himself.  Like his co-conspirators, he kept the identification cards of the women in order to keep them from leaving.  On several occasions, Taylor physically assaulted a woman because she did not earn enough money by engaging in commercial sex acts.  He also kept the money that the women earned, and if a woman did not earn enough money, he would order her to continue until she had.  Taylor also admitted that he brought an adult woman from Memphis to New Orleans and elsewhere for the purpose of forcing and coercing her to engage in prostitution.  The co-conspirators operated out of certain motels, including the Riviera, which generally did not report their activities to the police.  The defendants rented multiple rooms at the Riviera where the women would meet prostitution clients and paid higher rates for the rooms because of the increased traffic. Former Riviera Motel owner, Kanubhai Patel, 75, of Kenner, Louisiana, was also sentenced today to five years probation and ordered to pay a $10,000 fine.  On July 1, 2015, Patel pleaded guilty to benefitting financially from human trafficking.  Robinson was sentenced to 294 months in prison on May 4, 2016.  He previously pleaded guilty to one count of conspiring to commit sex trafficking and one count of sex trafficking. Williams and Brown have also pleaded guilty to conspiracy to engage in sex trafficking by force, fraud and coercion, and are awaiting sentencing. On Oct. 3, 2014, a grand jury in the Eastern District of Louisiana returned a second superseding indictment charging Phillips and Ellis, along with Robinson, Brown and Williams, with sex trafficking conspiracy and varying counts of sex trafficking and transportation for prostitution.  The second superseding indictment also charged Patel.  Taylor was charged separately on March 28, 2014. This case was investigated jointly by the FBI’s New Orleans Division and HSI’s New Orleans Field Office, with assistance from the FBI’s Memphis Division.  This case is being prosecuted by Trial Attorney Christine M. Siscaretti of the Civil Rights Division’s Criminal Section and Assistant U.S. Attorney Julia K. Evans of the Eastern District of Louisiana.

,id,contents,neg
14,14-248,"The Department of Justice announced that this morning John W. Ng, 58, of Albuquerque, N.M., made his initial appearance in federal court on a criminal complaint charging him with a hate crime offense. This charge is related to anti-Semitic threats Ng made against a Jewish woman who owns and operates the Nosh Jewish Delicatessen and Bakery in Albuquerque. Ng was arrested by the FBI on March 7, 2014, based on a criminal complaint alleging that he interfered with the victim’s federally protected rights by threatening her and interfering with her business because of her religion. According to the criminal complaint, between Jan. 22, 2014, and Feb. 8, 2014, Ng allegedly posted threatening anti-Semitic notes on and in the vicinity of the victim’s business. A criminal complaint merely establishes probable cause, and Ng is presumed innocent unless proven guilty. If convicted on the offense charged in the criminal complaint, Ng faces a maximum statutory penalty of one year in prison. This matter was investigated by the Albuquerque Division of the FBI and is being prosecuted by Assistant U.S. Attorney Mark T. Baker of the U.S. Attorney’s Office for the District of New Mexico and Trial Attorney AeJean Cha of the U.S. Department of Justice’s Civil Rights Division.",0.308
35,13-312,"John Hall, 27, an Aryan Brotherhood member and inmate at the Federal Correctional Institution (FCI) in Seagoville, Texas, was sentenced today by U.S. District Judge Reed O’Connor after pleading guilty to violating the Matthew Shepard and James Byrd Jr. Hate Crimes Prevention Act stemming from his assault of a fellow inmate, whom he believed to be gay, the Department of Justice announced. Hall assaulted his fellow inmate with a dangerous weapon, causing bodily injury to the victim on Dec. 20, 2011. Hall was sentenced to serve 71 months in prison to be served consecutively with the sentence he is currently serving. The assault occurred on Dec. 20, 2011, inside the FCI Seagoville when Hall targeted and attacked the victim, a fellow inmate, because he believed the victim was gay or involved in a sexual relationship with another male inmate. Hall repeatedly punched, kicked and stomped on the victim’s face with his shod feet, a dangerous weapon, while yelling a homophobic slur. The victim lost consciousness during the assault and suffered multiple lacerations to his face. The victim also sustained a fractured eye socket, lost a tooth, fractured other teeth and was treated at a hospital for the injuries he sustained during Hall’s unprovoked attack. Hall pleaded guilty to violating the Matthew Shepard and James Byrd Jr. Hate Crimes Prevention Act on Nov. 8, 2012. “Brutality and violence based on sexual orientation has no place in a civilized society,” said Thomas E. Perez, Assistant Attorney General for the Civil Rights Division. “The Justice Department is committed to using all the tools in our law enforcement arsenal, including the Matthew Shepard and James Byrd Jr. Hate Crimes Prevention Act, to prosecute acts motivated by hate.” “This prosecution sends a clear message that this office, in partnership with attorneys in the department’s Civil Rights Division, will prioritize and aggressively prosecute hate crimes and others civil rights violations in North Texas,” said U.S. Attorney Sarah R. Saldaña of the Northern District of Texas. This case was investigated by the FBI Dallas Division. The case was prosecuted by Assistant U.S. Attorney Errin Martin and Trial Attorney Adriana Vieco of the Civil Rights Division.",0.301

D. With the dataframe from part C, find the mean compound sentiment score for each of the three topics in `topics_clean` using group_by and agg.

E. Add a 1 sentence interpretation of why we might see the variation in scores (remember that compound is a standardized summary where -1 is most negative; +1 is most positive)

In [ ]:

mean_compound = (doj_subset_wscore.groupby('topics_clean')
        .agg(mean_compound=('compound', 'mean'))
        .reset_index()
)

print(mean_compound)

# Variation in scores likely shows differences in 
# nature of cases discussed since topics with things like violent crimes, trafficking,
# or hate crimes have very strong negative language whereas other topics
#like public corruption convictions, or outreach initiatives used
# more positive language.

                                                   topics_clean  mean_compound
0                               Access to Justice; Civil Rights       0.969117
1                                                  Civil Rights      -0.089995
2             Civil Rights; Counterterrorism; National Security      -0.992400
3                                     Civil Rights; Cyber Crime      -0.998900
4                                Civil Rights; Drug Trafficking      -0.997300
5             Civil Rights; Drug Trafficking; Human Trafficking      -0.999200
6                               Civil Rights; Firearms Offenses      -0.997300
7                                     Civil Rights; Hate Crimes      -0.838915
8                               Civil Rights; Human Trafficking      -0.978522
9                                     Civil Rights; Immigration       0.610992
10                 Civil Rights; Indian Country Law and Justice      -0.961200
11                             Civil Rights; Labor & Employment       0.475357
12  Civil Rights; Labor & Employment; Servicemembers Initiative       0.992600
13                              Civil Rights; Public Corruption       0.992700
14                      Civil Rights; Servicemembers Initiative       0.811380
15                                      Civil Rights; StopFraud       0.587060
16                                  Civil Rights; Violent Crime      -0.893400
17                              Community Outreach; Hate Crimes       0.927800
18                          Cyber Crime; Project Safe Childhood      -0.571900
19                      Financial Fraud; Project Safe Childhood      -0.904600
20                               Firearms Offenses; Hate Crimes      -0.996500
21                                                  Hate Crimes      -0.930564
22                                    Hate Crimes; Civil Rights      -0.987600
23                Hate Crimes; Human Trafficking; Violent Crime      -0.997800
24                    Human Trafficking; Project Safe Childhood      -0.585491
25                     Opioids; Civil Rights; Human Trafficking      -0.920100
26                                       Project Safe Childhood      -0.674909
27                              Public Corruption; Civil Rights      -0.765000

# 2. Optional extra credit (2 points)

You notice that the pharmaceutical kickbacks press release we analyzed in question 1 was for an indictment, and that in the original data, there's not a clear label for whether a press release outlines an indictment (charging someone with a crime), a conviction (convicting them after that charge either via a settlement or trial), or a sentencing (how many years of prison or supervised release a defendant is sentenced to after their conviction).

You want to see if you can identify pairs of press releases where one press release is from one stage (e.g., indictment) and another is from a different stage (e.g., a sentencing).

You decide that one way to approach is to find the pairwise string similarity between each of the processed press releases in `doj_subset`. There are many ways to do this, so Google for some approaches, focusing on ones that work well for entire documents rather than small strings.

Find the top two pairs (so four press releases total)-- do they seem like different stages of the same crime or just press releases covering similar crimes?